import { saveFile } from './creator-api.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);let current=null,verifiedCode='',querying=false,timer;
const read=(storage,key,fallback)=>{try{return JSON.parse(storage.getItem(key)||'null')??fallback;}catch{return fallback;}};
const receipts=[read(sessionStorage,'niuma-pack-pending-checkout',null),read(sessionStorage,'niuma-pending-checkout',null),read(sessionStorage,'niuma-support-pending-checkout',null),...read(localStorage,'niuma-pack-order-receipts-v1',[])].filter(item=>item&&typeof item.orderNo==='string'&&typeof item.buyerToken==='string');
const unique=[...new Map(receipts.map(item=>[item.orderNo,item])).values()];
const requested=params.get('order')||params.get('orderNo'),active=localStorage.getItem('niuma-pack-active-order-v1');
current=unique.find(item=>item.orderNo===(requested||active))||unique[0]||null;
if(!current&&!params.has('history')&&!requested)location.replace('claim.html');
const message=(text)=>{$('flow-status').textContent=text;};
async function legacy(path,headers={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(10000),headers});const body=await response.json().catch(()=>null);if(!response.ok||!body)throw new Error('原服务暂时无法恢复该记录，请保留凭据稍后重试。');return body;}
function auth(receipt){return receipt.buyerToken?{authorization:'Bearer '+receipt.buyerToken}:{'x-gongde-access-code':verifiedCode};}
async function download(receipt,button){button.disabled=true;message('正在通过原服务验证交付资格…');try{const response=await fetch('/api/gongde/orders/'+encodeURIComponent(receipt.orderNo)+'/package?format=batch',{credentials:'same-origin',headers:auth(receipt)});if(!response.ok)throw new Error('原订单暂时无法下载，记录与权益仍保留；请稍后重试或联系项目，不要重新付款。');const blob=await response.blob();const name=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/i)?.[1]||'niuma-historical-appearances.nmgpacks';saveFile(blob,name);message('原文件已交给浏览器，请查看下载进度。下载完成后可保存并使用兼容客户端永久离线导入。');}catch(error){message(error.message);}finally{button.disabled=false;}}
async function query(){if(!current||querying)return;querying=true;clearTimeout(timer);$('legacy-download').hidden=true;try{const result=await legacy('/api/gongde/orders/'+encodeURIComponent(current.orderNo),auth(current));const order=result.order;if(!order||typeof order.state!=='string')throw new Error('原订单状态尚未确认，不代表付款或交付成功。');$('legacy-order-status').textContent=current.orderNo+' · '+order.state;if(order.state==='FULFILLED'){message('服务器已确认原订单履行状态。仅提供合法原文件，不重新付款。');$('legacy-download').hidden=order.purchaseKind==='support'||current.purchaseKind==='support';}else if(order.state==='PAID'){message('服务器已确认原付款，正在等待历史交付准备完成。');timer=setTimeout(query,5000);}else if(['PENDING_PAYMENT','PENDING'].includes(order.state)){message('原订单尚未确认付款。本项目已停止新收费，不在此生成付款码。若此前已付，请稍后查询原记录。');}else{message('原服务返回 '+order.state+'；本页不会删除记录或伪装恢复成功。请联系项目处理原承诺。');}}catch(error){message(error.message);}finally{querying=false;}}
for(const receipt of unique){const row=document.createElement('li'),button=document.createElement('button');row.append(document.createTextNode(receipt.orderNo+' '));button.textContent='查询原记录';button.onclick=()=>{current=receipt;void query();};row.append(button);$('legacy-list').append(row);}
if(!unique.length)$('legacy-list').textContent='本浏览器暂无可验证订单凭据。请在原浏览器恢复或私下联系项目。';
$('legacy-refresh').onclick=()=>void query();$('legacy-download').onclick=()=>void download(current,$('legacy-download'));
$('legacy-access-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const code=form.elements.code.value.trim().toUpperCase().replace(/\s+/g,'');const headers={'x-gongde-access-code':code};const access=await legacy('/api/gongde/access',headers);if(access.ownsOfficialPass!==true)throw new Error('原权益尚未确认。');const result=await legacy('/api/gongde/access/orders',headers);if(!Array.isArray(result.orders))throw new Error('原交付列表尚未确认。');verifiedCode=code;form.elements.code.value='';$('legacy-access-orders').replaceChildren();for(const order of result.orders.filter(item=>item.state==='FULFILLED'&&item.purchaseKind!=='support')){const row=document.createElement('li'),downloadButton=document.createElement('button');row.textContent=order.orderNo+' ';downloadButton.textContent='恢复原交付';downloadButton.onclick=()=>void download(order,downloadButton);row.append(downloadButton);$('legacy-access-orders').append(row);}message('原权益已由服务验证；仅恢复原承诺范围，不开放新收费。');}catch(error){message(error.message);}finally{button.disabled=false;}};
addEventListener('pagehide',()=>clearTimeout(timer),{once:true});if(current)void query();
